name: Docker Trivy Artifactory Pipeline using Python

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-scan:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: Demo-App
      TAG: latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
